# Generated by Django 4.1 on 2022-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=33)),
                ('apellido', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.PositiveIntegerField()),
                ('dni', models.IntegerField(unique=True)),
                ('empleado_asignado', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugares', models.CharField(max_length=33)),
                ('fecha_de_entrada', models.DateField()),
                ('fecha_de_salida', models.DateField()),
            ],
        ),
    ]
