# Generated by Django 4.1.1 on 2022-09-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_remove_comentario_paquete_turistico'),
        ('AppTurismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='comentario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUser.comentario'),
        ),
    ]
