# Generated by Django 4.1.1 on 2022-09-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurismo', '0002_paqueteturistico_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteturistico',
            name='comentario',
        ),
    ]
