# Generated by Django 4.1.1 on 2022-09-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurismo', '0003_remove_paqueteturistico_comentario'),
        ('AppUser', '0003_remove_comentario_paquete_turistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='paquete_turistico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTurismo.paqueteturistico'),
        ),
    ]
